name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create static site
        run: |
          # Create index.html
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Motivational Quote Generator</title>
            <style>
              body {
                font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                margin: 0;
                padding: 0;
                background-color: #000;
                color: #fff;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                text-align: center;
                overflow: hidden;
              }
              .container {
                max-width: 800px;
                padding: 2rem;
                position: relative;
                z-index: 1;
              }
              h1 {
                font-size: 2.5rem;
                margin-bottom: 1.5rem;
              }
              p {
                font-size: 1.25rem;
                margin-bottom: 2rem;
                line-height: 1.6;
              }
              .neon-text {
                text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #0ff, 0 0 20px #0ff, 0 0 25px #0ff;
                animation: neon 1.5s ease-in-out infinite alternate;
              }
              @keyframes neon {
                from {
                  text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #0ff, 0 0 20px #0ff, 0 0 25px #0ff;
                }
                to {
                  text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #f0f, 0 0 20px #f0f, 0 0 25px #f0f;
                }
              }
              .ball {
                position: absolute;
                border-radius: 50%;
                z-index: 0;
                box-shadow: 0 0 20px currentColor;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1 class="neon-text">Motivational Quote Generator</h1>
              <p>This app is being deployed to GitHub Pages. Check back soon for the full interactive experience!</p>
              <p>In the meantime, remember: <span class="neon-text">"The journey of a thousand miles begins with a single step."</span></p>
            </div>
            <script>
              // Create neon colored balls
              function createBall() {
                const ball = document.createElement('div');
                ball.className = 'ball';
                
                // Random position
                const top = Math.random() * window.innerHeight;
                const left = Math.random() * window.innerWidth;
                
                // Random color
                const colors = ['#ff00ff', '#00ffff', '#ffff00', '#00ff00', '#ff0099', '#9D00FF'];
                const color = colors[Math.floor(Math.random() * colors.length)];
                
                // Random size
                const size = Math.random() * 30 + 20;
                
                ball.style.color = color;
                ball.style.background = color;
                ball.style.top = `${top}px`;
                ball.style.left = `${left}px`;
                ball.style.width = `${size}px`;
                ball.style.height = `${size}px`;
                
                document.body.appendChild(ball);
                
                // Animate the ball
                animateBall(ball);
              }
              
              function animateBall(ball) {
                // Random speed
                const speedX = (Math.random() - 0.5) * 5;
                const speedY = (Math.random() - 0.5) * 5;
                
                let posX = parseFloat(ball.style.left);
                let posY = parseFloat(ball.style.top);
                
                function move() {
                  posX += speedX;
                  posY += speedY;
                  
                  // Bounce off walls
                  if (posX <= 0 || posX >= window.innerWidth - parseFloat(ball.style.width)) {
                    speedX = -speedX;
                  }
                  
                  if (posY <= 0 || posY >= window.innerHeight - parseFloat(ball.style.height)) {
                    speedY = -speedY;
                  }
                  
                  ball.style.left = `${posX}px`;
                  ball.style.top = `${posY}px`;
                  
                  requestAnimationFrame(move);
                }
                
                move();
              }
              
              // Create balls
              for (let i = 0; i < 20; i++) {
                createBall();
              }
              
              // Handle window resize
              window.addEventListener('resize', () => {
                // Clear existing balls
                document.querySelectorAll('.ball').forEach(ball => ball.remove());
                
                // Create new balls
                for (let i = 0; i < 20; i++) {
                  createBall();
                }
              });
            </script>
          </body>
          </html>
          EOF
          
          # Create .nojekyll file to disable Jekyll processing
          touch .nojekyll

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Create a new branch for deployment
          git checkout --orphan gh-pages
          
          # Remove everything except index.html and .nojekyll
          git rm -rf .
          git add index.html .nojekyll
          
          # Commit changes
          git commit -m "Deploy to GitHub Pages"
          
          # Force push to gh-pages branch
          git push -f origin gh-pages
