name: Deploy to GitHub Pages with JGD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm init -y
          npm install next react react-dom
          npm install -D tailwindcss postcss autoprefixer @types/node @types/react @types/react-dom typescript
          npm install -D class-variance-authority clsx tailwind-merge
          npm install -D @radix-ui/react-slot @radix-ui/react-label
      
      - name: Setup Next.js
        run: |
          mkdir -p app components/ui lib
          echo '@tailwind base;
          @tailwind components;
          @tailwind utilities;' > app/globals.css
      
      - name: Build
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          clean: true

