name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Create docs directory
        run: |
          mkdir -p docs
          
          # Create index.html in docs directory
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Motivational Quote Generator</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
                margin: 0;
                padding: 0;
                background-color: #000;
                color: #fff;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                text-align: center;
                overflow: hidden;
              }
              .container {
                max-width: 800px;
                padding: 2rem;
                position: relative;
                z-index: 1;
              }
              h1 {
                font-size: 2.5rem;
                margin-bottom: 1.5rem;
              }
              p {
                font-size: 1.25rem;
                margin-bottom: 2rem;
                line-height: 1.6;
              }
              .neon-text {
                text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #0ff, 0 0 20px #0ff, 0 0 25px #0ff;
                animation: neon 1.5s ease-in-out infinite alternate;
              }
              @keyframes neon {
                from {
                  text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #0ff, 0 0 20px #0ff, 0 0 25px #0ff;
                }
                to {
                  text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #f0f, 0 0 20px #f0f, 0 0 25px #f0f;
                }
              }
              .ball {
                position: absolute;
                width: 50px;
                height: 50px;
                border-radius: 50%;
                animation: float 15s linear infinite;
                z-index: 0;
                box-shadow: 0 0 20px currentColor;
              }
              @keyframes float {
                0% { transform: translate(0, 0); }
                100% { transform: translate(calc(100vw - 100px), calc(100vh - 100px)); }
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1 class="neon-text">Motivational Quote Generator</h1>
              <p>This app is being deployed to GitHub Pages. Check back soon for the full interactive experience!</p>
              <p>In the meantime, remember: <span class="neon-text">"The journey of a thousand miles begins with a single step."</span></p>
            </div>
            <script>
              // Create neon colored balls
              function createBall() {
                const ball = document.createElement('div');
                ball.className = 'ball';
                
                // Random position
                const top = Math.random() * 100;
                const left = Math.random() * 100;
                
                // Random color
                const colors = ['#ff00ff', '#00ffff', '#ffff00', '#00ff00', '#ff0099', '#9D00FF'];
                const color = colors[Math.floor(Math.random() * colors.length)];
                
                // Random size
                const size = Math.random() * 30 + 20;
                
                // Random animation duration
                const duration = Math.random() * 20 + 10;
                
                // Random direction
                const startX = Math.random() * window.innerWidth;
                const startY = Math.random() * window.innerHeight;
                const endX = Math.random() * window.innerWidth;
                const endY = Math.random() * window.innerHeight;
                
                ball.style.color = color;
                ball.style.background = color;
                ball.style.top = `${startY}px`;
                ball.style.left = `${startX}px`;
                ball.style.width = `${size}px`;
                ball.style.height = `${size}px`;
                ball.style.animationDuration = `${duration}s`;
                
                // Create a unique animation for this ball
                const styleSheet = document.styleSheets[0];
                const animationName = `float-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
                const keyframes = `
                  @keyframes ${animationName} {
                    0% { transform: translate(0, 0); }
                    25% { transform: translate(${Math.random() * 100}vw, ${Math.random() * 100}vh); }
                    50% { transform: translate(${Math.random() * 100}vw, ${Math.random() * 100}vh); }
                    75% { transform: translate(${Math.random() * 100}vw, ${Math.random() * 100}vh); }
                    100% { transform: translate(0, 0); }
                  }
                `;
                styleSheet.insertRule(keyframes, styleSheet.cssRules.length);
                
                ball.style.animation = `${animationName} ${duration}s linear infinite`;
                
                document.body.appendChild(ball);
              }
              
              // Create 20 balls
              for (let i = 0; i < 20; i++) {
                createBall();
              }
            </script>
          </body>
          </html>
          EOF
          
          # Create .nojekyll file to disable Jekyll processing
          touch docs/.nojekyll
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
